"use client"

import { useMemo, useState } from "react"
import type { DespesaFinanceira, FinanceConfig, FichaTecnica, Insumo, VendaFinanceira } from "@/lib/types"
import { calcularVenda, canaisFinanceiros, classificarCmv, defaultFinanceConfig, formasPagamento, pontoEquilibrio, resumoFinanceiro, custoFichaOficial, formatarMoeda } from "@/lib/finance-engine"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { BarChart3, Calculator, CircleDollarSign, Plus, Receipt, Settings, Target, TrendingUp } from "lucide-react"

interface Props { fichas: FichaTecnica[]; insumos: Insumo[]; vendas?: VendaFinanceira[]; despesas?: DespesaFinanceira[]; config?: FinanceConfig; onAddVenda?: (venda: VendaFinanceira) => void; onAddDespesa?: (despesa: DespesaFinanceira) => void }
const money = formatarMoeda
const today = new Date().toISOString().slice(0, 10)

export function FinanceiroCentral({ fichas, insumos, vendas = [], despesas = [], config = defaultFinanceConfig, onAddVenda, onAddDespesa }: Props) {
  const [produtoId, setProdutoId] = useState(fichas[0]?.id ?? ""), [quantidade, setQuantidade] = useState("1"), [canal, setCanal] = useState<any>("salao"), [forma, setForma] = useState<any>("pix"), [desconto, setDesconto] = useState("0")
  const [competencia, setCompetencia] = useState(today), [periodo, setPeriodo] = useState("mes"), [despesa, setDespesa] = useState({ descricao: "", categoria: "Outros", valor: "", tipo: "variavel" as DespesaFinanceira["tipo"] })
  const produto = fichas.find(f => f.id === produtoId), cmv = produto ? custoFichaOficial(produto, insumos) : 0
  const preview = produto ? calcularVenda({ id: "preview", data: today, canal, formaPagamento: forma, produtoId: produto.id, produtoNome: produto.nome, quantidade: Number(quantidade) || 0, precoUnitario: produto.precoVenda, cmvUnitario: cmv, desconto: Number(desconto) || 0 }, config) : null
  const resumo = useMemo(() => resumoFinanceiro(vendas, despesas), [vendas, despesas])
  const pe = pontoEquilibrio(resumo.custosFixos, resumo.mcPercentual, resumo.ticketMedio), falta = Math.max(0, pe.faturamento - resumo.faturamentoBruto), progresso = pe.faturamento > 0 ? Math.min(100, resumo.faturamentoBruto / pe.faturamento * 100) : 0
  const cmvPct = resumo.faturamentoBruto > 0 ? resumo.cmv / resumo.faturamentoBruto * 100 : 0
  function registrarVenda() { if (preview && onAddVenda) onAddVenda(preview) }
  function registrarDespesa() { if (!onAddDespesa || !despesa.descricao || Number(despesa.valor) <= 0) return; onAddDespesa({ id: crypto.randomUUID(), descricao: despesa.descricao, categoria: despesa.categoria, valor: Number(despesa.valor), tipo: despesa.tipo, dataPagamento: today, competencia: competencia.slice(0, 7), recorrente: false, createdAt: new Date().toISOString() }); setDespesa({ descricao: "", categoria: "Outros", valor: "", tipo: "variavel" }) }
  const cards = [["Faturamento do período", resumo.faturamentoBruto, CircleDollarSign], ["Receita líquida", resumo.receitaLiquida, TrendingUp], ["CMV", resumo.cmv, Receipt], ["Resultado operacional", resumo.lucroOperacional, BarChart3]] as const
  return <div className="flex flex-col gap-6">
    <div className="flex flex-wrap items-end gap-3"><div className="grid gap-2"><Label>Período</Label><Select value={periodo} onValueChange={setPeriodo}><SelectTrigger className="w-44"><SelectValue /></SelectTrigger><SelectContent>{[["hoje", "Hoje"], ["ontem", "Ontem"], ["semana", "Esta semana"], ["mes", "Mês atual"], ["anterior", "Mês anterior"], ["ano", "Ano atual"]].map(([v, l]) => <SelectItem key={v} value={v}>{l}</SelectItem>)}</SelectContent></Select></div><p className="pb-2 text-sm text-muted-foreground">Os indicadores, DRE e relatórios seguem o período selecionado.</p></div>
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{cards.map(([label, value, Icon]) => <Card key={label}><CardContent className="flex items-center gap-3 pt-6"><div className="rounded-xl bg-primary/10 p-3 text-primary"><Icon className="size-5" /></div><div><p className="text-xl font-semibold">{money(value)}</p><p className="text-xs text-muted-foreground">{label}</p></div></CardContent></Card>)}</div>
    <Tabs defaultValue="lancar" className="flex flex-col gap-4"><TabsList className="w-fit"><TabsTrigger value="lancar">Lançar movimento</TabsTrigger><TabsTrigger value="dre">DRE gerencial</TabsTrigger><TabsTrigger value="relatorios">Relatórios</TabsTrigger><TabsTrigger value="metas">Equilíbrio</TabsTrigger><TabsTrigger value="config">Configurações</TabsTrigger></TabsList>
      <TabsContent value="lancar" className="grid gap-4 lg:grid-cols-2"><Card><CardHeader><CardTitle className="flex items-center gap-2"><Plus className="size-4 text-primary" /> Registrar venda</CardTitle></CardHeader><CardContent className="flex flex-col gap-4"><div className="grid gap-2"><Label>Produto</Label><Select value={produtoId} onValueChange={setProdutoId}><SelectTrigger><SelectValue placeholder="Selecione" /></SelectTrigger><SelectContent>{fichas.map(f => <SelectItem key={f.id} value={f.id}>{f.nome} — {money(f.precoVenda)}</SelectItem>)}</SelectContent></Select></div><div className="grid gap-3 sm:grid-cols-2"><div className="grid gap-2"><Label>Quantidade</Label><Input type="number" min="1" value={quantidade} onChange={e => setQuantidade(e.target.value)} /></div><div className="grid gap-2"><Label>Desconto</Label><Input type="number" min="0" value={desconto} onChange={e => setDesconto(e.target.value)} /></div><div className="grid gap-2"><Label>Canal</Label><Select value={canal} onValueChange={setCanal}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{canaisFinanceiros.map(([v, l]) => <SelectItem key={v} value={v}>{l}</SelectItem>)}</SelectContent></Select></div><div className="grid gap-2"><Label>Pagamento</Label><Select value={forma} onValueChange={setForma}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{formasPagamento.map(([v, l]) => <SelectItem key={v} value={v}>{l}</SelectItem>)}</SelectContent></Select></div></div>{preview && <div className="rounded-lg bg-muted p-3 text-sm"><div className="flex justify-between"><span>Valor bruto</span><strong>{money(preview.valorBruto)}</strong></div><div className="flex justify-between"><span>Taxas</span><strong>{money(preview.taxaTotalValor)}</strong></div><div className="flex justify-between"><span>CMV</span><strong>{money(preview.cmvTotalNaVenda)}</strong></div><div className="flex justify-between"><span>Margem estimada</span><strong>{money(preview.margemContribuicao)}</strong></div></div>}<Button onClick={registrarVenda} className="w-full">Registrar venda</Button></CardContent></Card>
        <Card><CardHeader><CardTitle className="flex items-center gap-2"><Receipt className="size-4 text-primary" /> Registrar despesa</CardTitle></CardHeader><CardContent className="flex flex-col gap-4"><div className="grid gap-2"><Label>Descrição</Label><Input value={despesa.descricao} onChange={e => setDespesa({ ...despesa, descricao: e.target.value })} /></div><div className="grid gap-3 sm:grid-cols-2"><div className="grid gap-2"><Label>Categoria</Label><Input value={despesa.categoria} onChange={e => setDespesa({ ...despesa, categoria: e.target.value })} /></div><div className="grid gap-2"><Label>Valor</Label><Input type="number" value={despesa.valor} onChange={e => setDespesa({ ...despesa, valor: e.target.value })} /></div><div className="grid gap-2"><Label>Tipo</Label><Select value={despesa.tipo} onValueChange={v => setDespesa({ ...despesa, tipo: v as DespesaFinanceira["tipo"] })}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="fixa">Fixa</SelectItem><SelectItem value="variavel">Variável</SelectItem><SelectItem value="extraordinaria">Extraordinária</SelectItem></SelectContent></Select></div><div className="grid gap-2"><Label>Competência</Label><Input type="month" value={competencia.slice(0, 7)} onChange={e => setCompetencia(e.target.value)} /></div></div><Button variant="outline" onClick={registrarDespesa} className="w-full">Registrar despesa</Button></CardContent></Card></TabsContent>
      <TabsContent value="dre"><Card><CardHeader><CardTitle>DRE gerencial — {periodo === "mes" ? "mês atual" : periodo}</CardTitle></CardHeader><CardContent className="flex flex-col gap-3 text-sm">{[["Faturamento bruto", resumo.faturamentoBruto], ["(-) Descontos", -resumo.descontos], ["(-) Taxas", -resumo.taxas], ["Receita líquida", resumo.receitaLiquida], ["(-) CMV", -resumo.cmv], ["Lucro bruto", resumo.lucroBruto], ["(-) Despesas variáveis", -resumo.despesasVariaveis], ["Margem de contribuição", resumo.margemContribuicao], ["(-) Custos fixos", -resumo.custosFixos], ["Resultado operacional", resumo.lucroOperacional]].map(([label, value]) => <div key={label as string} className="flex items-center justify-between border-b border-border py-2"><span>{label}</span><strong className={(value as number) < 0 ? "text-destructive" : undefined}>{money(value as number)}</strong></div>)}</CardContent></Card></TabsContent>
      <TabsContent value="relatorios" className="grid gap-4 lg:grid-cols-2"><Card><CardHeader><CardTitle>Resultado por canal</CardTitle></CardHeader><CardContent className="overflow-x-auto"><table className="w-full min-w-[620px] text-sm"><thead><tr className="border-b text-left"><th className="p-2">Canal</th><th className="p-2">Faturamento</th><th className="p-2">Taxas</th><th className="p-2">CMV</th><th className="p-2">MC</th></tr></thead><tbody>{canaisFinanceiros.slice(0, 4).map(([id, label]) => { const r = resumoFinanceiro(vendas.filter(v => v.canalNaVenda === id), []); return <tr key={id} className="border-b"><td className="p-2">{label}</td><td className="p-2">{money(r.faturamentoBruto)}</td><td className="p-2">{money(r.taxas)}</td><td className="p-2">{money(r.cmv)}</td><td className="p-2">{money(r.margemContribuicao)}</td></tr> })}</tbody></table></CardContent></Card><Card><CardHeader><CardTitle>Resultado por pagamento</CardTitle></CardHeader><CardContent className="overflow-x-auto"><table className="w-full min-w-[420px] text-sm"><thead><tr className="border-b text-left"><th className="p-2">Forma</th><th className="p-2">Faturamento</th><th className="p-2">Taxa</th><th className="p-2">Líquido</th></tr></thead><tbody>{formasPagamento.map(([id, label]) => { const r = resumoFinanceiro(vendas.filter(v => v.formaPagamentoNaVenda === id), []); return <tr key={id} className="border-b"><td className="p-2">{label}</td><td className="p-2">{money(r.faturamentoBruto)}</td><td className="p-2">{money(r.taxas)}</td><td className="p-2">{money(r.receitaLiquida)}</td></tr> })}</tbody></table></CardContent></Card></TabsContent>
      <TabsContent value="metas" className="grid gap-4 md:grid-cols-3"><Card><CardContent className="flex flex-col gap-2 pt-6"><Target className="size-5 text-primary" /><p className="text-sm text-muted-foreground">Ponto de equilíbrio</p><p className="text-2xl font-semibold">{pe.faturamento ? money(pe.faturamento) : "Sem dados suficientes"}</p><p className="text-xs text-muted-foreground">Diário: {pe.faturamento ? money(pe.faturamento / 30) : "Sem dados suficientes"}</p></CardContent></Card><Card><CardContent className="flex flex-col gap-2 pt-6"><Calculator className="size-5 text-primary" /><p className="text-sm text-muted-foreground">Progresso</p><p className="text-2xl font-semibold">{progresso.toFixed(1)}%</p><p className="text-xs text-muted-foreground">Falta: {money(falta)}</p></CardContent></Card><Card><CardContent className="flex flex-col gap-2 pt-6"><TrendingUp className="size-5 text-primary" /><p className="text-sm text-muted-foreground">CMV meta</p><p className="text-2xl font-semibold">{cmvPct.toFixed(1)}%</p><p className="text-xs text-muted-foreground">{classificarCmv(cmvPct, config.cmvMetaPercentual)} — meta {config.cmvMetaPercentual}%</p></CardContent></Card></TabsContent>
      <TabsContent value="config"><Card><CardHeader><CardTitle className="flex items-center gap-2"><Settings className="size-4 text-primary" /> Configurações financeiras</CardTitle></CardHeader><CardContent className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{formasPagamento.map(([id, label]) => <div key={id} className="grid gap-2"><Label>{label} (%)</Label><Input type="number" value={config.taxasPagamento[id]} readOnly /></div>)}<div className="grid gap-2"><Label>99Food (%)</Label><Input type="number" value={config.taxasCanal["99food"]?.taxaPercentual ?? config.taxas?.["99food"] ?? 0} readOnly /></div><div className="grid gap-2"><Label>CMV meta (%)</Label><Input type="number" value={config.cmvMetaPercentual} readOnly /></div><p className="col-span-full text-sm text-muted-foreground">A edição de taxas e metas deve ser habilitada no fluxo administrativo owner/admin, sem permitir alteração por operador.</p></CardContent></Card></TabsContent>
    </Tabs>
  </div>
}
